import type { Exercise } from "@/lib/exercise-schemas";

/**
 * Seed exercise library — bodyweight, home-friendly, chosen to avoid
 * unnecessary spinal loading (docs/01_Project_Charter.md).
 *
 * These are widely used general mobility/stability movements, NOT a
 * prescription for any specific curve. The app does not diagnose or
 * personalise clinically (docs/04_Clinical_Guardrails.md); a clinician's
 * plan always overrides this default set.
 */
export const EXERCISE_SEED: Exercise[] = [
  {
    id: "ex-diaphragmatic-breathing",
    name: "Diaphragmatic Breathing",
    domain: "breathing",
    difficulty: "beginner",
    durationSeconds: 120,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Napas lewat hidung ke perut", "Buang napas panjang lewat mulut"],
    contraindications: ["Pusing berat saat napas dalam"],
    progressionId: "ex-90-90-breathing",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-90-90-breathing",
    name: "90/90 Breathing",
    domain: "breathing",
    difficulty: "intermediate",
    durationSeconds: 150,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Betis di atas kursi", "Tekan punggung bawah ke lantai saat buang napas"],
    contraindications: ["Nyeri panggul akut"],
    progressionId: null,
    regressionId: "ex-diaphragmatic-breathing",
    videoUrl: null,
  },
  {
    id: "ex-cat-cow",
    name: "Cat-Cow",
    domain: "mobility",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Gerak pelan mengikuti napas", "Jangan paksa ujung gerakan"],
    contraindications: ["Nyeri tajam saat ekstensi punggung"],
    progressionId: "ex-thread-the-needle",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-thread-the-needle",
    name: "Thread the Needle",
    domain: "mobility",
    difficulty: "intermediate",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Rotasi dari punggung atas", "Ikuti tangan dengan pandangan"],
    contraindications: ["Nyeri bahu saat menumpu"],
    progressionId: null,
    regressionId: "ex-cat-cow",
    videoUrl: null,
  },
  {
    id: "ex-dead-bug",
    name: "Dead Bug",
    domain: "core",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung bawah nempel lantai", "Gerak lawan tangan-kaki pelan"],
    contraindications: ["Punggung bawah melengkung tidak terkontrol"],
    progressionId: "ex-bird-dog",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-bird-dog",
    name: "Bird Dog",
    domain: "core",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Panggul tetap rata", "Julurkan lawan tangan-kaki, tahan 2 detik"],
    contraindications: ["Nyeri saat ekstensi pinggul"],
    progressionId: null,
    regressionId: "ex-dead-bug",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-left",
    name: "Side Plank (Kiri)",
    domain: "stability",
    difficulty: "intermediate",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "left",
    cues: ["Tubuh satu garis lurus", "Angkat panggul, jangan menekuk"],
    contraindications: ["Nyeri bahu tumpu", "Nyeri pinggang tajam"],
    progressionId: null,
    regressionId: "ex-side-plank-knees-left",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-knees-left",
    name: "Side Plank Lutut (Kiri)",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "left",
    cues: ["Tumpu di lutut", "Garis lurus bahu ke lutut"],
    contraindications: ["Nyeri bahu tumpu"],
    progressionId: "ex-side-plank-left",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-side-plank-right",
    name: "Side Plank (Kanan)",
    domain: "stability",
    difficulty: "intermediate",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "right",
    cues: ["Tubuh satu garis lurus", "Angkat panggul, jangan menekuk"],
    contraindications: ["Nyeri bahu tumpu", "Nyeri pinggang tajam"],
    progressionId: null,
    regressionId: "ex-side-plank-knees-right",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-knees-right",
    name: "Side Plank Lutut (Kanan)",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "right",
    cues: ["Tumpu di lutut", "Garis lurus bahu ke lutut"],
    contraindications: ["Nyeri bahu tumpu"],
    progressionId: "ex-side-plank-right",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-stance",
    name: "Single-Leg Stance",
    domain: "balance",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Fokus pandangan satu titik", "Ganti kaki tiap 30 detik"],
    contraindications: ["Vertigo", "Riwayat jatuh tanpa pegangan"],
    progressionId: "ex-single-leg-reach",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-reach",
    name: "Single-Leg Reach",
    domain: "balance",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Raih ke depan sambil jaga panggul rata", "Gerak terkontrol"],
    contraindications: ["Vertigo", "Nyeri lutut tumpu"],
    progressionId: null,
    regressionId: "ex-single-leg-stance",
    videoUrl: null,
  },
  {
    id: "ex-glute-bridge",
    name: "Glute Bridge",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Dorong lewat tumit", "Remas glute di atas, jangan lengkungkan pinggang"],
    contraindications: ["Kram hamstring", "Nyeri pinggang saat mengangkat panggul"],
    progressionId: "ex-single-leg-bridge",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-bridge",
    name: "Single-Leg Glute Bridge",
    domain: "strength",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Panggul tetap rata saat satu kaki", "Kontrol turunnya"],
    contraindications: ["Nyeri pinggang", "Kram hamstring"],
    progressionId: null,
    regressionId: "ex-glute-bridge",
    videoUrl: null,
  },
  {
    id: "ex-wall-sit",
    name: "Wall Sit",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung menempel dinding", "Paha sejajar lantai kalau mampu"],
    contraindications: ["Nyeri lutut menekuk beban"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-marching-in-place",
    name: "Marching in Place",
    domain: "conditioning",
    difficulty: "beginner",
    durationSeconds: 120,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Angkat lutut setinggi nyaman", "Napas teratur"],
    contraindications: ["Sesak napas", "Nyeri dada"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-child-pose",
    name: "Child's Pose",
    domain: "recovery",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Napas ke punggung", "Rileks bahu"],
    contraindications: ["Nyeri lutut menekuk penuh"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-supine-twist",
    name: "Supine Twist",
    domain: "recovery",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Rotasi pelan, kedua bahu tetap di lantai", "Tahan tanpa memaksa"],
    contraindications: ["Nyeri tajam saat rotasi"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  // Strength — push-up progression chain (all bodyweight).
  {
    id: "ex-wall-pushup",
    name: "Wall Push-up",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tubuh lurus dari kepala ke tumit", "Tekuk siku terkontrol"],
    contraindications: ["Nyeri bahu saat menekan"],
    progressionId: "ex-incline-pushup",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-incline-pushup",
    name: "Incline Push-up",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tumpu di meja/kursi kokoh", "Core aktif, jangan melengkung"],
    contraindications: ["Nyeri bahu saat menekan", "Nyeri pergelangan tangan"],
    progressionId: "ex-knee-pushup",
    regressionId: "ex-wall-pushup",
    videoUrl: null,
  },
  {
    id: "ex-knee-pushup",
    name: "Knee Push-up",
    domain: "strength",
    difficulty: "intermediate",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tumpu di lutut", "Garis lurus bahu ke lutut"],
    contraindications: ["Nyeri bahu saat menekan", "Nyeri lutut menumpu"],
    progressionId: "ex-full-pushup",
    regressionId: "ex-incline-pushup",
    videoUrl: null,
  },
  {
    id: "ex-full-pushup",
    name: "Full Push-up",
    domain: "strength",
    difficulty: "advanced",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tubuh satu garis", "Turun sampai dada dekat lantai"],
    contraindications: ["Nyeri bahu saat menekan", "Punggung bawah melengkung"],
    progressionId: null,
    regressionId: "ex-knee-pushup",
    videoUrl: null,
  },
  {
    id: "ex-split-squat",
    name: "Split Squat",
    domain: "strength",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Langkah satu kaki ke depan", "Turun lurus, lutut depan di atas mata kaki"],
    contraindications: ["Nyeri lutut menekuk beban", "Keseimbangan buruk tanpa pegangan"],
    progressionId: null,
    regressionId: "ex-wall-sit",
    videoUrl: null,
  },
  {
    id: "ex-reverse-lunge",
    name: "Reverse Lunge",
    domain: "strength",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Langkah mundur terkontrol", "Jaga badan tegak"],
    contraindications: ["Nyeri lutut", "Keseimbangan buruk"],
    progressionId: null,
    regressionId: "ex-wall-sit",
    videoUrl: null,
  },
  {
    id: "ex-calf-raise",
    name: "Calf Raise",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Angkat tumit pelan", "Tahan sebentar di atas, turun terkontrol"],
    contraindications: ["Nyeri tendon achilles"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  // Posture-focused (stability domain so the engine's posture boost picks them up).
  {
    id: "ex-wall-angel",
    name: "Wall Angel",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung & kepala nempel dinding", "Geser lengan naik-turun tetap menempel"],
    contraindications: ["Nyeri bahu saat mengangkat lengan"],
    progressionId: "ex-prone-ytw",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-prone-ytw",
    name: "Prone Y-T-W Raises",
    domain: "stability",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tengkurap, angkat lengan bentuk Y-T-W", "Remas tulang belikat"],
    contraindications: ["Nyeri bahu saat mengangkat", "Nyeri leher saat tengkurap"],
    progressionId: null,
    regressionId: "ex-wall-angel",
    videoUrl: null,
  },
  {
    id: "ex-chin-tuck",
    name: "Chin Tuck",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tarik dagu ke belakang (dobel chin)", "Tahan 3 detik, rileks"],
    contraindications: ["Pusing saat gerak leher", "Nyeri leher tajam"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-prone-press-up",
    name: "Prone Press-up",
    domain: "mobility",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tengkurap, dorong dada naik pakai lengan", "Panggul tetap di lantai"],
    contraindications: ["Nyeri tajam saat ekstensi punggung", "Nyeri menjalar ke kaki"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  // Core additions.
  {
    id: "ex-front-plank-knees",
    name: "Front Plank Lutut",
    domain: "core",
    difficulty: "beginner",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tumpu siku & lutut", "Garis lurus bahu ke lutut, core aktif"],
    contraindications: ["Nyeri bahu tumpu", "Nyeri pinggang saat menahan"],
    progressionId: "ex-front-plank",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-front-plank",
    name: "Front Plank",
    domain: "core",
    difficulty: "intermediate",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Tumpu siku & ujung kaki", "Panggul netral, jangan turun"],
    contraindications: ["Nyeri bahu tumpu", "Punggung bawah melengkung"],
    progressionId: "ex-hollow-hold",
    regressionId: "ex-front-plank-knees",
    videoUrl: null,
  },
  {
    id: "ex-hollow-hold",
    name: "Hollow-Body Hold",
    domain: "core",
    difficulty: "advanced",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung bawah nempel lantai", "Angkat bahu & kaki, tahan"],
    contraindications: ["Punggung bawah terangkat tak terkontrol", "Nyeri leher"],
    progressionId: null,
    regressionId: "ex-front-plank",
    videoUrl: null,
  },
];
