import type { Exercise } from "@/lib/exercise-schemas";

/**
 * Seed exercise library — bodyweight, home-friendly, chosen to avoid
 * unnecessary spinal loading (docs/01_Project_Charter.md).
 *
 * These are widely used general mobility/stability movements, NOT a
 * prescription for any specific curve. The app does not diagnose or
 * personalise clinically (docs/04_Clinical_Guardrails.md); a clinician's
 * plan always overrides this default set.
 */
export const EXERCISE_SEED: Exercise[] = [
  {
    id: "ex-diaphragmatic-breathing",
    name: "Diaphragmatic Breathing",
    domain: "breathing",
    difficulty: "beginner",
    durationSeconds: 120,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Napas lewat hidung ke perut", "Buang napas panjang lewat mulut"],
    contraindications: ["Pusing berat saat napas dalam"],
    progressionId: "ex-90-90-breathing",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-90-90-breathing",
    name: "90/90 Breathing",
    domain: "breathing",
    difficulty: "intermediate",
    durationSeconds: 150,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Betis di atas kursi", "Tekan punggung bawah ke lantai saat buang napas"],
    contraindications: ["Nyeri panggul akut"],
    progressionId: null,
    regressionId: "ex-diaphragmatic-breathing",
    videoUrl: null,
  },
  {
    id: "ex-cat-cow",
    name: "Cat-Cow",
    domain: "mobility",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Gerak pelan mengikuti napas", "Jangan paksa ujung gerakan"],
    contraindications: ["Nyeri tajam saat ekstensi punggung"],
    progressionId: "ex-thread-the-needle",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-thread-the-needle",
    name: "Thread the Needle",
    domain: "mobility",
    difficulty: "intermediate",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Rotasi dari punggung atas", "Ikuti tangan dengan pandangan"],
    contraindications: ["Nyeri bahu saat menumpu"],
    progressionId: null,
    regressionId: "ex-cat-cow",
    videoUrl: null,
  },
  {
    id: "ex-dead-bug",
    name: "Dead Bug",
    domain: "core",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung bawah nempel lantai", "Gerak lawan tangan-kaki pelan"],
    contraindications: ["Punggung bawah melengkung tidak terkontrol"],
    progressionId: "ex-bird-dog",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-bird-dog",
    name: "Bird Dog",
    domain: "core",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Panggul tetap rata", "Julurkan lawan tangan-kaki, tahan 2 detik"],
    contraindications: ["Nyeri saat ekstensi pinggul"],
    progressionId: null,
    regressionId: "ex-dead-bug",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-left",
    name: "Side Plank (Kiri)",
    domain: "stability",
    difficulty: "intermediate",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "left",
    cues: ["Tubuh satu garis lurus", "Angkat panggul, jangan menekuk"],
    contraindications: ["Nyeri bahu tumpu", "Nyeri pinggang tajam"],
    progressionId: null,
    regressionId: "ex-side-plank-knees-left",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-knees-left",
    name: "Side Plank Lutut (Kiri)",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "left",
    cues: ["Tumpu di lutut", "Garis lurus bahu ke lutut"],
    contraindications: ["Nyeri bahu tumpu"],
    progressionId: "ex-side-plank-left",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-side-plank-right",
    name: "Side Plank (Kanan)",
    domain: "stability",
    difficulty: "intermediate",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "right",
    cues: ["Tubuh satu garis lurus", "Angkat panggul, jangan menekuk"],
    contraindications: ["Nyeri bahu tumpu", "Nyeri pinggang tajam"],
    progressionId: null,
    regressionId: "ex-side-plank-knees-right",
    videoUrl: null,
  },
  {
    id: "ex-side-plank-knees-right",
    name: "Side Plank Lutut (Kanan)",
    domain: "stability",
    difficulty: "beginner",
    durationSeconds: 40,
    equipment: [],
    sideEmphasis: "right",
    cues: ["Tumpu di lutut", "Garis lurus bahu ke lutut"],
    contraindications: ["Nyeri bahu tumpu"],
    progressionId: "ex-side-plank-right",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-stance",
    name: "Single-Leg Stance",
    domain: "balance",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Fokus pandangan satu titik", "Ganti kaki tiap 30 detik"],
    contraindications: ["Vertigo", "Riwayat jatuh tanpa pegangan"],
    progressionId: "ex-single-leg-reach",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-reach",
    name: "Single-Leg Reach",
    domain: "balance",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Raih ke depan sambil jaga panggul rata", "Gerak terkontrol"],
    contraindications: ["Vertigo", "Nyeri lutut tumpu"],
    progressionId: null,
    regressionId: "ex-single-leg-stance",
    videoUrl: null,
  },
  {
    id: "ex-glute-bridge",
    name: "Glute Bridge",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Dorong lewat tumit", "Remas glute di atas, jangan lengkungkan pinggang"],
    contraindications: ["Kram hamstring", "Nyeri pinggang saat mengangkat panggul"],
    progressionId: "ex-single-leg-bridge",
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-single-leg-bridge",
    name: "Single-Leg Glute Bridge",
    domain: "strength",
    difficulty: "intermediate",
    durationSeconds: 60,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Panggul tetap rata saat satu kaki", "Kontrol turunnya"],
    contraindications: ["Nyeri pinggang", "Kram hamstring"],
    progressionId: null,
    regressionId: "ex-glute-bridge",
    videoUrl: null,
  },
  {
    id: "ex-wall-sit",
    name: "Wall Sit",
    domain: "strength",
    difficulty: "beginner",
    durationSeconds: 45,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Punggung menempel dinding", "Paha sejajar lantai kalau mampu"],
    contraindications: ["Nyeri lutut menekuk beban"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-marching-in-place",
    name: "Marching in Place",
    domain: "conditioning",
    difficulty: "beginner",
    durationSeconds: 120,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Angkat lutut setinggi nyaman", "Napas teratur"],
    contraindications: ["Sesak napas", "Nyeri dada"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-child-pose",
    name: "Child's Pose",
    domain: "recovery",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Napas ke punggung", "Rileks bahu"],
    contraindications: ["Nyeri lutut menekuk penuh"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
  {
    id: "ex-supine-twist",
    name: "Supine Twist",
    domain: "recovery",
    difficulty: "beginner",
    durationSeconds: 90,
    equipment: [],
    sideEmphasis: "bilateral",
    cues: ["Rotasi pelan, kedua bahu tetap di lantai", "Tahan tanpa memaksa"],
    contraindications: ["Nyeri tajam saat rotasi"],
    progressionId: null,
    regressionId: null,
    videoUrl: null,
  },
];
